#!/bin/bash

if [ -z "$1" ]; then
	echo "Fuck all not found"
	exit 1
fi

SCRIPT_TO_RUN=$(find ./installers/ -name "$1.sh")

if [ -z "$SCRIPT_TO_RUN" ]; then
	echo "Fuck all found"
	exit 2
fi

$SCRIPT_TO_RUN ${@:2}
